@startuml
class Elemento<T extends Comparable<T>>{
    - dato:T
    - siguiente:Elemento<T>
    + Elemento(dato:T)
    + getDato():T
    + setDato(dato:T):void
    + getSiguiente():Elemento<T>
    + setSiguiente(siguiente:Elemento<T>):void
}
class Pila<T extends Comparable<T>>{
    - cabeza:Elemento<T>
    + push(dato:T):void
    + pop():T
    + peek():T
    + isEmpty():boolean
}
class Cola<T extends Comparable<T>>{
    - cabeza:Elemento<T>
    - cola:Elemento<T>
    + enqueue(dato:T):void
    + dequeue():T
    + peek():T
    + isEmpty():boolean
}
class ListaCircular<T extends Comparable<T>>{
    - cabeza:Elemento<T>
    + insertar(dato:T):void
    + eliminar():T
    + peek():T
    + isEmpty():boolean
}
Pila*--Elemento
Cola*--Elemento
ListaCircular*--Elemento

note right of Pila::push(dato:T)
**LIFO**:Apila al incio
end note

note right of Cola::enqueue(dato:T)
**FIFO**: Apila al final
end note

note right of ListaCircular::insertar(dato:T)
**Circular**:Añade antes del bucle
end note

note right of Pila::pop()
**Elimina** y **Devuelve** el primer elemento
end note

note right of Cola::dequeue()
**Elimina** y **Devuelve** el primer elemento
end note

note right of ListaCircular::eliminar()
**Elimina** y **Devuelve** el primer elemento
end note

note right of Pila::peek()
**Devuelve** el primer elemento
end note

note right of Cola::peek()
**Devuelve** el primer elemento
end note

note right of ListaCircular::peek()
**Devuelve** el primer elemento
end note

note bottom of Elemento
**Clase Base**
Todas las estructuras las usan
end note

@enduml